services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: fixmyphone-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: fixmyphone_dev
      POSTGRES_USER: fixmyphone_user
      POSTGRES_PASSWORD: fixmyphone_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fixmyphone-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fixmyphone_user -d fixmyphone_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service for Development
  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      target: development
    container_name: fixmyphone-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5051
      DATABASE_URL: postgresql://fixmyphone_user:fixmyphone_password@postgres:5432/fixmyphone_dev
      DATABASE_PROD_URL: postgresql://fixmyphone_user:fixmyphone_password@postgres:5432/fixmyphone_dev
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRED_IN: 30d
      JWT_REFRESH_SECRET: dev-refresh-token-secret
      JWT_SECRET_SALT_ROUND: 12
      CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-demo-cloud}
      API_KEY: ${CLOUDINARY_API_KEY:-demo-key}
      API_SECRET: ${CLOUDINARY_API_SECRET:-demo-secret}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-pk_test_demo}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_demo}
    ports:
      - "5051:5051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fixmyphone-dev-network
    volumes:
      - ./api:/app
      - /app/node_modules
      - api_dev_uploads:/app/uploads

  # Frontend Client Service for Development  
  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      target: development
    container_name: fixmyphone-client-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5051/api/v1
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-pk_test_demo}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_demo}
    ports:
      - "3000:3000"
    depends_on:
      - api-dev
    networks:
      - fixmyphone-dev-network
    volumes:
      - ./client:/app
      - /app/node_modules
      - client_dev_next:/app/.next

networks:
  fixmyphone-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  api_dev_uploads:
    driver: local
  client_dev_next:
    driver: local
